-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sin_or_cos_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    t_in : IN STD_LOGIC_VECTOR (31 downto 0);
    do_cos : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sin_or_cos_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_C2 : STD_LOGIC_VECTOR (7 downto 0) := "11000010";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_83 : STD_LOGIC_VECTOR (7 downto 0) := "10000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv29_1FFFFFFF : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111111111111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ref_4oPi_table_100_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal ref_4oPi_table_100_V_ce0 : STD_LOGIC;
    signal ref_4oPi_table_100_V_q0 : STD_LOGIC_VECTOR (99 downto 0);
    signal second_order_float_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_2_ce0 : STD_LOGIC;
    signal second_order_float_2_q0 : STD_LOGIC_VECTOR (29 downto 0);
    signal second_order_float_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_3_ce0 : STD_LOGIC;
    signal second_order_float_3_q0 : STD_LOGIC_VECTOR (22 downto 0);
    signal second_order_float_s_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal second_order_float_s_ce0 : STD_LOGIC;
    signal second_order_float_s_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_21_reg_986 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_fu_236_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_V_reg_992 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_V_1_fu_246_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_V_1_reg_999 : STD_LOGIC_VECTOR (22 downto 0);
    signal closepath_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal closepath_reg_1005 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_285_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_12_reg_1016 : STD_LOGIC_VECTOR (3 downto 0);
    signal Med_V_reg_1021 : STD_LOGIC_VECTOR (79 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_25_reg_1026 : STD_LOGIC_VECTOR (57 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_12_i2_reg_1032 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1037 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_Val2_26_fu_365_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Val2_26_reg_1049 : STD_LOGIC_VECTOR (2 downto 0);
    signal Mx_V_fu_445_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal Mx_V_reg_1054 : STD_LOGIC_VECTOR (28 downto 0);
    signal Ex_V_fu_459_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Ex_V_reg_1059 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_527_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1064 : STD_LOGIC_VECTOR (0 downto 0);
    signal B_V_fu_559_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_V_reg_1070 : STD_LOGIC_VECTOR (21 downto 0);
    signal B_trunc_V_reg_1075 : STD_LOGIC_VECTOR (14 downto 0);
    signal not_do_cos_i_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_do_cos_i_reg_1080 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1100 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1106 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_5_fu_690_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal ret_V_5_reg_1114 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal cos_basis_fu_701_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cos_basis_reg_1119 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal result_V_reg_1124 : STD_LOGIC_VECTOR (28 downto 0);
    signal ret_V_fu_749_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_reg_1129 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_scaled_fixed2ieee_fu_218_ap_start : STD_LOGIC;
    signal grp_scaled_fixed2ieee_fu_218_ap_done : STD_LOGIC;
    signal grp_scaled_fixed2ieee_fu_218_ap_idle : STD_LOGIC;
    signal grp_scaled_fixed2ieee_fu_218_ap_ready : STD_LOGIC;
    signal grp_scaled_fixed2ieee_fu_218_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_scaled_fixed2ieee_fu_218_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_5_i_i_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_74_i_fu_593_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_s_fu_224_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal expv_op_i_fu_256_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal addr_V_fu_262_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_270_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_i_i_fu_289_p1 : STD_LOGIC_VECTOR (99 downto 0);
    signal r_V_9_fu_292_p2 : STD_LOGIC_VECTOR (99 downto 0);
    signal p_Result_22_fu_308_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ret_V_8_fu_322_p0 : STD_LOGIC_VECTOR (79 downto 0);
    signal ret_V_8_fu_322_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ret_V_8_fu_322_p2 : STD_LOGIC_VECTOR (103 downto 0);
    signal p_1_i_fu_353_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_371_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_bits_V_1_fu_375_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal p_Val2_8_fu_380_p3 : STD_LOGIC_VECTOR (57 downto 0);
    signal p_Result_i_i_fu_387_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_Result_23_fu_397_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_s_fu_405_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_24_fu_415_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_fu_423_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Mx_zeros_V_fu_431_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_15_i_fu_435_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal r_V_10_fu_439_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal storemerge_i_fu_358_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_i_fu_455_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sh_i_cast_fu_465_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal isNeg_fu_469_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_i_fu_477_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_fu_483_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_4_i_cast_fu_495_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_22_i_fu_503_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_21_i_fu_499_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_assign_4_i_cast6_fu_491_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_i_fu_509_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_i_fu_513_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0237_0_in_i_fu_519_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal not_do_cos_i_fu_573_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sin_basis_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_i_fu_549_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_25_fu_585_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_11_fu_972_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_12_fu_639_p0 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_12_fu_639_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal r_V_12_fu_639_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal B_squared_V_fu_613_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_13_fu_979_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal t1_V_fu_622_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_12_i_fu_645_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal lhs_V_fu_672_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal rhs_V_2_fu_676_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_14_i_fu_663_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_9_fu_680_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal rhs_V_19_cast_fu_686_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal cos_basis_fu_701_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Mx_V_read_assign_fu_714_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal r_V_14_fu_728_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_14_fu_728_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal r_V_14_fu_728_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal p_Ex_V_ret_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_fu_745_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_21_fu_756_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_27_fu_782_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_788_p18 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_826_p18 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_cast_fu_879_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_864_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_s_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_26_fu_760_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_2_fu_768_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_din_sign_V_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_results_sign_V_ret_fu_896_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_cast_fu_879_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_results_exp_V_ret_fu_904_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_or_cond_demorgan_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_or_cond_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_results_sig_V_ret_c_fu_937_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_V_3_fu_778_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Repl2_3_fu_911_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_6_fu_919_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_7_fu_950_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_28_fu_958_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_11_fu_972_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_fu_610_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_11_fu_972_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_13_fu_979_p0 : STD_LOGIC_VECTOR (14 downto 0);
    signal ret_i_i_fu_968_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal r_V_12_fu_639_p10 : STD_LOGIC_VECTOR (44 downto 0);
    signal r_V_13_fu_979_p00 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_14_fu_728_p10 : STD_LOGIC_VECTOR (57 downto 0);
    signal ret_V_8_fu_322_p00 : STD_LOGIC_VECTOR (103 downto 0);
    signal ret_V_8_fu_322_p10 : STD_LOGIC_VECTOR (103 downto 0);

    component scaled_fixed2ieee IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_V : IN STD_LOGIC_VECTOR (28 downto 0);
        prescale : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_mux_83_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component FFT_mux_164_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (0 downto 0);
        din9 : IN STD_LOGIC_VECTOR (0 downto 0);
        din10 : IN STD_LOGIC_VECTOR (0 downto 0);
        din11 : IN STD_LOGIC_VECTOR (0 downto 0);
        din12 : IN STD_LOGIC_VECTOR (0 downto 0);
        din13 : IN STD_LOGIC_VECTOR (0 downto 0);
        din14 : IN STD_LOGIC_VECTOR (0 downto 0);
        din15 : IN STD_LOGIC_VECTOR (0 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component FFT_mul_mul_15ns_fYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component FFT_mul_mul_15ns_g8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component sin_or_cos_float_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (99 downto 0) );
    end component;


    component sin_or_cos_float_cud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component sin_or_cos_float_dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component sin_or_cos_float_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    ref_4oPi_table_100_V_U : component sin_or_cos_float_bkb
    generic map (
        DataWidth => 100,
        AddressRange => 13,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ref_4oPi_table_100_V_address0,
        ce0 => ref_4oPi_table_100_V_ce0,
        q0 => ref_4oPi_table_100_V_q0);

    second_order_float_2_U : component sin_or_cos_float_cud
    generic map (
        DataWidth => 30,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_2_address0,
        ce0 => second_order_float_2_ce0,
        q0 => second_order_float_2_q0);

    second_order_float_3_U : component sin_or_cos_float_dEe
    generic map (
        DataWidth => 23,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_3_address0,
        ce0 => second_order_float_3_ce0,
        q0 => second_order_float_3_q0);

    second_order_float_s_U : component sin_or_cos_float_eOg
    generic map (
        DataWidth => 15,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_order_float_s_address0,
        ce0 => second_order_float_s_ce0,
        q0 => second_order_float_s_q0);

    grp_scaled_fixed2ieee_fu_218 : component scaled_fixed2ieee
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_scaled_fixed2ieee_fu_218_ap_start,
        ap_done => grp_scaled_fixed2ieee_fu_218_ap_done,
        ap_idle => grp_scaled_fixed2ieee_fu_218_ap_idle,
        ap_ready => grp_scaled_fixed2ieee_fu_218_ap_ready,
        in_V => result_V_reg_1124,
        prescale => ret_V_reg_1129,
        ap_return => grp_scaled_fixed2ieee_fu_218_ap_return);

    FFT_mux_83_1_1_1_U3 : component FFT_mux_83_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_1,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_0,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        din8 => p_Val2_26_fu_365_p3,
        dout => tmp_fu_527_p10);

    FFT_mux_164_1_1_1_U4 : component FFT_mux_164_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 1,
        din9_WIDTH => 1,
        din10_WIDTH => 1,
        din11_WIDTH => 1,
        din12_WIDTH => 1,
        din13_WIDTH => 1,
        din14_WIDTH => 1,
        din15_WIDTH => 1,
        din16_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_0,
        din3 => ap_const_lv1_1,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_1,
        din7 => ap_const_lv1_0,
        din8 => ap_const_lv1_0,
        din9 => ap_const_lv1_1,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_1,
        din13 => ap_const_lv1_0,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        din16 => p_Result_27_fu_782_p3,
        dout => tmp_2_fu_788_p18);

    FFT_mux_164_1_1_1_U5 : component FFT_mux_164_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 1,
        din9_WIDTH => 1,
        din10_WIDTH => 1,
        din11_WIDTH => 1,
        din12_WIDTH => 1,
        din13_WIDTH => 1,
        din14_WIDTH => 1,
        din15_WIDTH => 1,
        din16_WIDTH => 4,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_0,
        din1 => ap_const_lv1_0,
        din2 => ap_const_lv1_1,
        din3 => ap_const_lv1_0,
        din4 => ap_const_lv1_1,
        din5 => ap_const_lv1_1,
        din6 => ap_const_lv1_0,
        din7 => ap_const_lv1_1,
        din8 => ap_const_lv1_1,
        din9 => ap_const_lv1_0,
        din10 => ap_const_lv1_1,
        din11 => ap_const_lv1_1,
        din12 => ap_const_lv1_0,
        din13 => ap_const_lv1_1,
        din14 => ap_const_lv1_0,
        din15 => ap_const_lv1_0,
        din16 => p_Result_27_fu_782_p3,
        dout => tmp_3_fu_826_p18);

    FFT_mul_mul_15ns_fYi_U6 : component FFT_mul_mul_15ns_fYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => r_V_11_fu_972_p0,
        din1 => r_V_11_fu_972_p1,
        dout => r_V_11_fu_972_p2);

    FFT_mul_mul_15ns_g8j_U7 : component FFT_mul_mul_15ns_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => r_V_13_fu_979_p0,
        din1 => second_order_float_s_q0,
        dout => r_V_13_fu_979_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_scaled_fixed2ieee_fu_218_ap_done = ap_const_logic_1))) then 
                    ap_return_preg <= ret_i_i_fu_968_p1;
                end if; 
            end if;
        end if;
    end process;


    grp_scaled_fixed2ieee_fu_218_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_scaled_fixed2ieee_fu_218_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_scaled_fixed2ieee_fu_218_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_scaled_fixed2ieee_fu_218_ap_ready = ap_const_logic_1)) then 
                    grp_scaled_fixed2ieee_fu_218_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                B_V_reg_1070 <= B_V_fu_559_p1;
                B_trunc_V_reg_1075 <= p_0237_0_in_i_fu_519_p3(21 downto 7);
                Ex_V_reg_1059 <= Ex_V_fu_459_p2;
                Mx_V_reg_1054 <= r_V_10_fu_439_p2(57 downto 29);
                not_do_cos_i_reg_1080 <= not_do_cos_i_fu_573_p2;
                p_Val2_26_reg_1049 <= p_Val2_26_fu_365_p3;
                tmp_5_reg_1100 <= tmp_5_fu_600_p2;
                tmp_7_reg_1106 <= tmp_7_fu_605_p2;
                tmp_reg_1064 <= tmp_fu_527_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                Med_V_reg_1021 <= r_V_9_fu_292_p2(99 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                closepath_reg_1005 <= closepath_fu_250_p2;
                p_Result_21_reg_986 <= p_Val2_s_fu_224_p1(31 downto 31);
                tmp_12_reg_1016 <= tmp_12_fu_285_p1;
                tmp_V_1_reg_999 <= tmp_V_1_fu_246_p1;
                tmp_V_reg_992 <= p_Val2_s_fu_224_p1(30 downto 23);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                cos_basis_reg_1119 <= cos_basis_fu_701_p3;
                result_V_reg_1124 <= r_V_14_fu_728_p2(57 downto 29);
                ret_V_reg_1129 <= ret_V_fu_749_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_Val2_25_reg_1026 <= ret_V_8_fu_322_p2(76 downto 19);
                tmp_6_reg_1037 <= tmp_6_fu_348_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                ret_V_5_reg_1114 <= ret_V_5_fu_690_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((closepath_reg_1005 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_12_i2_reg_1032 <= ret_V_8_fu_322_p2(79 downto 77);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_scaled_fixed2ieee_fu_218_ap_done, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_scaled_fixed2ieee_fu_218_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    B_V_fu_559_p1 <= p_0237_0_in_i_fu_519_p3(22 - 1 downto 0);
    B_squared_V_fu_613_p4 <= r_V_11_fu_972_p2(29 downto 15);
    Ex_V_fu_459_p2 <= std_logic_vector(unsigned(storemerge_i_fu_358_p3) - unsigned(tmp_18_i_fu_455_p1));
    Mx_V_fu_445_p4 <= r_V_10_fu_439_p2(57 downto 29);
    Mx_V_read_assign_fu_714_p3 <= 
        ap_const_lv29_1FFFFFFF when (cos_basis_fu_701_p3(0) = '1') else 
        Mx_V_reg_1054;
    Mx_bits_V_1_fu_375_p2 <= std_logic_vector(unsigned(ap_const_lv58_0) - unsigned(p_Val2_25_reg_1026));
    Mx_zeros_V_fu_431_p1 <= val_assign_fu_423_p3(5 - 1 downto 0);
    addr_V_fu_262_p3 <= 
        ap_const_lv8_3F when (closepath_fu_250_p2(0) = '1') else 
        expv_op_i_fu_256_p2;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_scaled_fixed2ieee_fu_218_ap_done, ap_CS_fsm_state7)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_scaled_fixed2ieee_fu_218_ap_done = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_scaled_fixed2ieee_fu_218_ap_done, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_scaled_fixed2ieee_fu_218_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(grp_scaled_fixed2ieee_fu_218_ap_done, ap_CS_fsm_state7, ret_i_i_fu_968_p1, ap_return_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_scaled_fixed2ieee_fu_218_ap_done = ap_const_logic_1))) then 
            ap_return <= ret_i_i_fu_968_p1;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    closepath_fu_250_p2 <= "1" when (unsigned(tmp_V_fu_236_p4) < unsigned(ap_const_lv8_7E)) else "0";
    cos_basis_fu_701_p0 <= (0=>do_cos, others=>'-');
    cos_basis_fu_701_p3 <= 
        tmp_s_fu_696_p2 when (cos_basis_fu_701_p0(0) = '1') else 
        tmp_reg_1064;
    expv_op_i_fu_256_p2 <= std_logic_vector(signed(ap_const_lv8_C2) + signed(tmp_V_fu_236_p4));
    grp_scaled_fixed2ieee_fu_218_ap_start <= grp_scaled_fixed2ieee_fu_218_ap_start_reg;
    isNeg_fu_469_p3 <= Ex_V_fu_459_p2(7 downto 7);
        lhs_V_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t1_V_fu_622_p4),30));

    not_do_cos_i_fu_573_p0 <= (0=>do_cos, others=>'-');
    not_do_cos_i_fu_573_p2 <= (not_do_cos_i_fu_573_p0 xor ap_const_lv1_1);
    not_or_cond_demorgan_fu_927_p2 <= (tmp_6_reg_1037 and tmp_5_reg_1100);
    not_or_cond_fu_931_p2 <= (not_or_cond_demorgan_fu_927_p2 xor ap_const_lv1_1);
    not_tmp_s_fu_886_p2 <= (tmp_7_reg_1106 xor ap_const_lv1_1);
    or_cond_fu_871_p2 <= (tmp_6_reg_1037 and tmp_5_reg_1100);
    p_0237_0_in_i_fu_519_p3 <= 
        tmp_24_i_fu_509_p1 when (isNeg_fu_469_p3(0) = '1') else 
        tmp_25_i_fu_513_p2;
    p_1_i_fu_353_p2 <= std_logic_vector(signed(ap_const_lv8_83) + signed(tmp_V_reg_992));
    p_Ex_V_ret_fu_707_p3 <= 
        ap_const_lv8_0 when (cos_basis_fu_701_p3(0) = '1') else 
        Ex_V_reg_1059;
    p_Repl2_3_fu_911_p3 <= 
        p_din_sign_V_fu_875_p2 when (or_cond_fu_871_p2(0) = '1') else 
        p_results_sign_V_ret_fu_896_p3;
    p_Result_22_fu_308_p3 <= (ap_const_lv1_1 & tmp_V_1_reg_999);
    p_Result_23_fu_397_p3 <= (p_Result_i_i_fu_387_p4 & ap_const_lv1_1);
    p_Result_24_fu_415_p3 <= (ap_const_lv2_3 & p_Result_s_fu_405_p4);
    p_Result_25_fu_585_p3 <= (sin_basis_fu_579_p2 & p_Result_i_fu_549_p4);
    p_Result_26_fu_760_p3 <= p_Val2_21_fu_756_p1(31 downto 31);
    p_Result_27_fu_782_p3 <= (p_Result_21_reg_986 & p_Val2_26_reg_1049);
    p_Result_28_fu_958_p4 <= ((p_Repl2_3_fu_911_p3 & ret_V_6_fu_919_p3) & ret_V_7_fu_950_p3);
    p_Result_i_fu_549_p4 <= p_0237_0_in_i_fu_519_p3(28 downto 22);
    p_Result_i_i_fu_387_p4 <= p_Val2_8_fu_380_p3(57 downto 29);
    
    p_Result_s_fu_405_p4_proc : process(p_Result_23_fu_397_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(30+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable p_Result_s_fu_405_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(30 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1D(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := p_Result_23_fu_397_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(30-1-unsigned(ap_const_lv32_1D(5-1 downto 0)));
            for p_Result_s_fu_405_p4_i in 0 to 30-1 loop
                v0_cpy(p_Result_s_fu_405_p4_i) := p_Result_23_fu_397_p3(30-1-p_Result_s_fu_405_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(30-1 downto 0)))));
        res_mask := res_mask(30-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_s_fu_405_p4 <= resvalue(30-1 downto 0);
    end process;

    p_Val2_21_fu_756_p1 <= grp_scaled_fixed2ieee_fu_218_ap_return;
    p_Val2_26_fu_365_p3 <= 
        ap_const_lv3_0 when (closepath_reg_1005(0) = '1') else 
        tmp_12_i2_reg_1032;
    p_Val2_8_fu_380_p3 <= 
        Mx_bits_V_1_fu_375_p2 when (tmp_13_fu_371_p1(0) = '1') else 
        p_Val2_25_reg_1026;
    p_Val2_s_fu_224_p1 <= t_in;
    p_cast_cast_fu_879_p0 <= (0=>do_cos, others=>'-');
    p_cast_cast_fu_879_p3 <= 
        ap_const_lv8_7F when (p_cast_cast_fu_879_p0(0) = '1') else 
        ap_const_lv8_0;
    p_din_sign_V_fu_875_p2 <= (p_Result_21_reg_986 and not_do_cos_i_reg_1080);
    p_results_exp_V_ret_fu_904_p3 <= 
        ap_const_lv8_FF when (tmp_7_reg_1106(0) = '1') else 
        tmp_V_2_fu_768_p4;
    p_results_sig_V_ret_c_fu_937_p3 <= 
        ap_const_lv23_7FFFFF when (not_or_cond_fu_931_p2(0) = '1') else 
        ap_const_lv23_0;
    p_results_sign_V_ret_fu_896_p3 <= 
        not_tmp_s_fu_886_p2 when (tmp_8_fu_891_p2(0) = '1') else 
        p_Result_26_fu_760_p3;
    r_V_10_fu_439_p2 <= std_logic_vector(shift_left(unsigned(p_Val2_8_fu_380_p3),to_integer(unsigned('0' & tmp_15_i_fu_435_p1(31-1 downto 0)))));
    r_V_11_fu_972_p0 <= r_V_fu_610_p1(15 - 1 downto 0);
    r_V_11_fu_972_p1 <= r_V_fu_610_p1(15 - 1 downto 0);
    r_V_12_fu_639_p0 <= second_order_float_3_q0;
    r_V_12_fu_639_p1 <= r_V_12_fu_639_p10(22 - 1 downto 0);
    r_V_12_fu_639_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_V_reg_1070),45));
    r_V_12_fu_639_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_12_fu_639_p0) * signed('0' &r_V_12_fu_639_p1))), 45));
    r_V_13_fu_979_p0 <= r_V_13_fu_979_p00(15 - 1 downto 0);
    r_V_13_fu_979_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_squared_V_fu_613_p4),30));
    r_V_14_fu_728_p0 <= ret_V_5_reg_1114;
    r_V_14_fu_728_p1 <= r_V_14_fu_728_p10(29 - 1 downto 0);
    r_V_14_fu_728_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_V_read_assign_fu_714_p3),58));
    r_V_14_fu_728_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_14_fu_728_p0) * signed('0' &r_V_14_fu_728_p1))), 58));
    r_V_9_fu_292_p2 <= std_logic_vector(shift_left(unsigned(ref_4oPi_table_100_V_q0),to_integer(unsigned('0' & tmp_7_i_i_fu_289_p1(31-1 downto 0)))));
    r_V_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B_trunc_V_reg_1075),30));
    ref_4oPi_table_100_V_address0 <= tmp_5_i_i_fu_280_p1(4 - 1 downto 0);

    ref_4oPi_table_100_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            ref_4oPi_table_100_V_ce0 <= ap_const_logic_1;
        else 
            ref_4oPi_table_100_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_5_fu_690_p2 <= std_logic_vector(unsigned(ret_V_9_fu_680_p2) + unsigned(rhs_V_19_cast_fu_686_p1));
    ret_V_6_fu_919_p3 <= 
        p_cast_cast_fu_879_p3 when (or_cond_fu_871_p2(0) = '1') else 
        p_results_exp_V_ret_fu_904_p3;
    ret_V_7_fu_950_p3 <= 
        p_results_sig_V_ret_c_fu_937_p3 when (tmp_9_fu_945_p2(0) = '1') else 
        tmp_V_3_fu_778_p1;
    ret_V_8_fu_322_p0 <= ret_V_8_fu_322_p00(80 - 1 downto 0);
    ret_V_8_fu_322_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Med_V_reg_1021),104));
    ret_V_8_fu_322_p1 <= ret_V_8_fu_322_p10(24 - 1 downto 0);
    ret_V_8_fu_322_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_22_fu_308_p3),104));
    ret_V_8_fu_322_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_8_fu_322_p0) * unsigned(ret_V_8_fu_322_p1), 104));
    ret_V_9_fu_680_p2 <= std_logic_vector(signed(lhs_V_fu_672_p1) + signed(rhs_V_2_fu_676_p1));
    ret_V_fu_749_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(rhs_V_fu_745_p1));
    ret_i_i_fu_968_p1 <= p_Result_28_fu_958_p4;
        rhs_V_19_cast_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_i_fu_663_p4),30));

        rhs_V_2_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_i_fu_645_p4),30));

        rhs_V_fu_745_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Ex_V_ret_fu_707_p3),9));

    second_order_float_2_address0 <= tmp_74_i_fu_593_p1(8 - 1 downto 0);

    second_order_float_2_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            second_order_float_2_ce0 <= ap_const_logic_1;
        else 
            second_order_float_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_3_address0 <= tmp_74_i_fu_593_p1(8 - 1 downto 0);

    second_order_float_3_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            second_order_float_3_ce0 <= ap_const_logic_1;
        else 
            second_order_float_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    second_order_float_s_address0 <= tmp_74_i_fu_593_p1(8 - 1 downto 0);

    second_order_float_s_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            second_order_float_s_ce0 <= ap_const_logic_1;
        else 
            second_order_float_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        sh_assign_4_i_cast6_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_483_p3),32));

        sh_assign_4_i_cast_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_483_p3),29));

        sh_i_cast_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ex_V_fu_459_p2),9));

    sin_basis_fu_579_p2 <= (tmp_fu_527_p10 xor not_do_cos_i_fu_573_p2);
    storemerge_i_fu_358_p3 <= 
        p_1_i_fu_353_p2 when (closepath_reg_1005(0) = '1') else 
        ap_const_lv8_0;
    t1_V_fu_622_p4 <= second_order_float_2_q0(29 downto 1);
    tmp_12_fu_285_p1 <= addr_V_fu_262_p3(4 - 1 downto 0);
    tmp_12_i_fu_645_p4 <= r_V_12_fu_639_p2(44 downto 23);
    tmp_13_fu_371_p1 <= p_Val2_26_fu_365_p3(1 - 1 downto 0);
    tmp_14_i_fu_663_p4 <= r_V_13_fu_979_p2(29 downto 16);
    tmp_15_i_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_V_fu_431_p1),58));
    tmp_18_i_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_zeros_V_fu_431_p1),8));
    tmp_1_fu_270_p4 <= addr_V_fu_262_p3(7 downto 4);
    tmp_20_i_fu_477_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sh_i_cast_fu_465_p1));
    tmp_21_i_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Mx_V_fu_445_p4),32));
    tmp_22_i_fu_503_p2 <= std_logic_vector(shift_right(unsigned(Mx_V_fu_445_p4),to_integer(unsigned('0' & sh_assign_4_i_cast_fu_495_p1(29-1 downto 0)))));
    tmp_24_i_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_i_fu_503_p2),32));
    tmp_25_i_fu_513_p2 <= std_logic_vector(shift_left(unsigned(tmp_21_i_fu_499_p1),to_integer(unsigned('0' & sh_assign_4_i_cast6_fu_491_p1(31-1 downto 0)))));
    tmp_4_fu_864_p3 <= 
        tmp_2_fu_788_p18 when (cos_basis_reg_1119(0) = '1') else 
        tmp_3_fu_826_p18;
    tmp_5_fu_600_p2 <= "1" when (tmp_V_reg_992 = ap_const_lv8_0) else "0";
    tmp_5_i_i_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_270_p4),64));
    tmp_6_fu_348_p2 <= "1" when (tmp_V_1_reg_999 = ap_const_lv23_0) else "0";
    tmp_74_i_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_25_fu_585_p3),64));
    tmp_7_fu_605_p2 <= "1" when (tmp_V_reg_992 = ap_const_lv8_FF) else "0";
    tmp_7_i_i_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_reg_1016),100));
    tmp_8_fu_891_p2 <= (tmp_7_reg_1106 or tmp_4_fu_864_p3);
    tmp_9_fu_945_p2 <= (tmp_7_reg_1106 or or_cond_fu_871_p2);
    tmp_V_1_fu_246_p1 <= p_Val2_s_fu_224_p1(23 - 1 downto 0);
    tmp_V_2_fu_768_p4 <= p_Val2_21_fu_756_p1(30 downto 23);
    tmp_V_3_fu_778_p1 <= p_Val2_21_fu_756_p1(23 - 1 downto 0);
    tmp_V_fu_236_p4 <= p_Val2_s_fu_224_p1(30 downto 23);
    tmp_s_fu_696_p2 <= (tmp_reg_1064 xor ap_const_lv1_1);
    ush_fu_483_p3 <= 
        tmp_20_i_fu_477_p2 when (isNeg_fu_469_p3(0) = '1') else 
        sh_i_cast_fu_465_p1;
    
    val_assign_fu_423_p3_proc : process(p_Result_24_fu_415_p3)
    begin
        val_assign_fu_423_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_24_fu_415_p3(i) = '1' then
                val_assign_fu_423_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

end behav;
